from . import nationality
from . import parent
from . import academic_year
from . import education_stade
from . import student
from . import fees_type
from . import fees_rules
from . import fees_payment
from . import payment_batches
